### ISSUE TITLE
Packages do not appear in any search

### ISSUE THREAD

**Issue by anbuc** [sonatype-nexus-community/nexus-repository-composer#131]
Searching for a composer package currently does not work. I think that is the reason why cleanup policies, while we can assign them now, do not work at all. This becomes apparent when trying to preview a cleanup policy and no package ever comes up, regardless how the filters are configured. This also applies to the default search functionality (`/#browse/search`)

**Comment by lerminou** [comment]
I'm upgrading to the new Nexus version (3.45)
When booting, I see this log: It may be linked
 ```
2023-01-04 12:28:02,866+0100 ERROR [quartz-12-thread-5]  *SYSTEM org.sonatype.nexus.repository.content.search.elasticsearch.SearchFacetImpl - Unable to rebuild search index for repository composer-packagist-proxy
org.sonatype.nexus.repository.MissingFacetException: No facet of type ContentFacet attached to repository composer-packagist-proxy
	at org.sonatype.nexus.repository.manager.internal.RepositoryImpl.facet(RepositoryImpl.java:327)
	at org.sonatype.nexus.repository.content.search.elasticsearch.SearchFacetImpl.rebuildComponentIndex(SearchFacetImpl.java:156)
	at org.sonatype.nexus.repository.content.search.elasticsearch.SearchFacetImpl.rebuildIndex(SearchFacetImpl.java:147)
	at org.sonatype.nexus.repository.content.search.elasticsearch.SearchFacetImpl$$EnhancerByGuice$$436803389.GUICE$TRAMPOLINE(<generated>)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:74)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$GuardImpl.run(StateGuard.java:272)
	at org.sonatype.nexus.common.stateguard.GuardedInterceptor.invoke(GuardedInterceptor.java:54)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
	at com.google.inject.internal.InterceptorStackCallback.invoke(InterceptorStackCallback.java:55)
	at org.sonatype.nexus.repository.content.search.elasticsearch.SearchFacetImpl$$EnhancerByGuice$$436803389.rebuildIndex(<generated>)
	at org.sonatype.nexus.repository.search.index.RebuildIndexTask.execute(RebuildIndexTask.java:33)
	at org.sonatype.nexus.repository.RepositoryTaskSupport.execute(RepositoryTaskSupport.java:79)
	at org.sonatype.nexus.scheduling.TaskSupport.call(TaskSupport.java:100)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.doExecute(QuartzTaskJob.java:143)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.execute(QuartzTaskJob.java:106)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.sonatype.nexus.quartz.internal.QuartzThreadPool.lambda$0(QuartzThreadPool.java:145)
	at org.sonatype.nexus.thread.internal.MDCAwareRunnable.run(MDCAwareRunnable.java:40)
	at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
	at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by githoober** [comment]
Can confirm that too. No search results for composer packages.

**Comment by Mmasson-01** [comment]
Can confirm this too, also no results from the search API 
- `${NEXUS_URL}/service/rest/v1/search\?repository\=composer-hosted`
- - `${NEXUS_URL}/service/rest/v1/search\?repository\=packagist`

**Comment by ibilalovic** [comment]
Upgrading my Nexus in 3.45.1-01 with nexus-repository-composer 0.0.29 ang got the same :
- no new composer packages list when using nexus 3 search bar.
- no return for composer in API call

**Comment by pju51** [comment]
hello
any news on this issue ?

**Comment by ricardoee** [comment]
Following.  Have this exact same issue.

**Comment by tsukasa-mixer** [comment]
I confirm, it doesn't find anything.

**Comment by afshin-hoseini** [comment]
I got the same issue here. It simply doesn't show anything on the cleanup preview.
OSS 3.70.2-01
