### ISSUE TITLE
The http://xxx:8081/repository/xh-composer/packages.json file could not be downloaded (HTTP/1.1 500 Server Error)

### ISSUE THREAD

**Issue by zwp201301** [sonatype-nexus-community/nexus-repository-composer#170]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

composer config repo.nxrmproxy '{"type": "composer", "url": "http://172.27.3.242:8081/repository/xh-composer/"}'
composer config repositories.packagist false
composer config secure-http false

composer install ,  throw error:

The http://xxx:8081/repository/xh-composer/packages.json file could not be downloaded (HTTP/1.1 500 Server Error)

* **What feature or behavior is this required for?**
```
composer install
You are running Composer with SSL/TLS protection disabled.
Composer is operating significantly slower than normal because you do not have the PHP curl extension enabled.
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Warning: Accessing 172.27.3.242 over http which is an insecure protocol.
 
In RemoteFilesystem.php line 423:
                                                                                                                                 
  The "[http://172.27.3.242:8081/repository/xh-composer/packages.json"](http://172.27.3.242:8081/repository/xh-composer/packages.json) file could not be downloaded (HTTP/1.1 500 Server Error)
```

```
2024-11-06 02:15:10,492+0000 WARN  [qtp1271282310-105]  *UNKNOWN org.sonatype.nexus.repository.httpbridge.internal.ViewServlet - Failure servicing: GET /repository/xh-composer/packages.json
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
	at org.sonatype.nexus.repository.composer.internal.proxy.ComposerProxyFacet.generatePackagesJson(ComposerProxyFacet.java:190)
	at org.sonatype.nexus.repository.composer.internal.proxy.ComposerProxyFacet.store(ComposerProxyFacet.java:120)
	at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.doGet(ProxyFacetSupport.java:356)
	at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.lambda$1(ProxyFacetSupport.java:321)
	at org.sonatype.nexus.common.cooperation2.ScopedCooperation2Support$ScopedCooperation2Builder.perform(ScopedCooperation2Support.java:85)
	at org.sonatype.nexus.common.cooperation2.datastore.internal.CooperatingFuture.performCall(CooperatingFuture.java:126)
	at org.sonatype.nexus.common.cooperation2.datastore.internal.CooperatingFuture.call(CooperatingFuture.java:68)
	at org.sonatype.nexus.common.cooperation2.ScopedCooperation2Support$ScopedCooperation2Builder.cooperate(ScopedCooperation2Support.java:102)
```
* **How could we solve this issue? (Not knowing is okay!)**

I donot know how do handle it ? 

please help me, if you also happened like this.

**Comment by stklcode** [comment]
I guess this is a proxy repository with an upstream thaw does not provide a package list (which is optional), so generation from list fails.

If this is the case, it should be fixed by #165 in v0.1.7 and later now.
