### ISSUE TITLE
composer-proxy not working !

### ISSUE THREAD

**Issue by firmlyshell** [sonatype-nexus-community/nexus-repository-composer#39]
I use nexus-repository-composer-0.0.2.jar at https://hub.docker.com/r/sonatype/nexus3 docker images .
I config composer-proxy find this exception.

java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:882)
	at org.sonatype.nexus.repository.composer.internal.ComposerProxyFacetImpl.generatePackagesJson(ComposerProxyFacetImpl.java:164)
	at org.sonatype.nexus.repository.composer.internal.ComposerProxyFacetImpl.store(ComposerProxyFacetImpl.java:106)
	at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.doGet(ProxyFacetSupport.java:263)
	at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.lambda$1(ProxyFacetSupport.java:237)
	at org.sonatype.nexus.common.io.CooperatingFuture.performCall(CooperatingFuture.java:122)
	at org.sonatype.nexus.common.io.CooperatingFuture.call(CooperatingFuture.java:64)
	at org.sonatype.nexus.common.io.ScopedCooperationFactorySupport$ScopedCooperation.cooperate(ScopedCooperationFactorySupport.java:99)
	at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.get(ProxyFacetSupport.java:228)
	at org.sonatype.nexus.repository.proxy.ProxyHandler.handle(ProxyHandler.java:50)
	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
	at org.sonatype.nexus.repository.storage.UnitOfWorkHandler.handle(UnitOfWorkHandler.java:39)
	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
	at org.sonatype.nexus.repository.view.handlers.ContentHeadersHandler.handle(ContentHeadersHandler.java:45)
	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
	at org.sonatype.nexus.repository.http.PartialFetchHandler.handle(PartialFetchHandler.java:59)
	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
	at org.sonatype.nexus.repository.view.handlers.ConditionalRequestHandler.handle(ConditionalRequestHandler.java:72)
	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
	at org.sonatype.nexus.repository.cache.NegativeCacheHandler.handle(NegativeCacheHandler.java:56)
	at org.sonatype.nexus.repository.view.Context.proceed(Context.java:80)
	at com.sonatype.nexus.clm.internal.FirewallContributedHandler.handle(FirewallContributedHandler.java:87)

**Comment by aqm1152** [comment]
Any luck, I have been getting the same thing lately on this. More specifically on the composer cli front, the error is that this is 
```
 [Composer\Downloader\TransportException]
  The "https://baseURL/repository/composer-proxy/packages.json" file could not be downloaded (HTTP/1.1 500 Server Error)
  ```

**Comment by pengjun-gz** [comment]
> Any luck, I have been getting the same thing lately on this. More specifically on the composer cli front, the error is that this is
> 
> ```
>  [Composer\Downloader\TransportException]
>   The "https://baseURL/repository/composer-proxy/packages.json" file could not be downloaded (HTTP/1.1 500 Server Error)
> ```
> 
> Reinstalled composer-proxy thinking that might solve it but now having this issue with every composer install
> 
> ```
> org.sonatype.nexus.repository.httpbridge.internal.ViewServlet - Failure servicing: GET /repository/composer-proxy/packages.json
> java.lang.NullPointerException: null
> ```
> 
> Any ideas anyone of what the reason for this could be? I have gone up and down the google verse and nothing is really helping ..

it let me down，do you solve it ？
